### ISSUE TITLE
Student Portal

### ISSUE THREAD

**Issue by nixpulvis** [nixpulvis/bottlenose#5]
<img width="1280" alt="screen shot 2016-06-10 at 4 21 24 pm" src="https://cloud.githubusercontent.com/assets/715947/15977544/662a2ef8-2f27-11e6-9d18-39ff5cbb964f.png">

- [x] Non clickable due date and clickable submissions shouldn't look the same.
- [x] The current score column should either show a % sign, or have a denominator for total possible points, and it should be clickable to see the most recent submission.
- [x] Most recent submission is adjacent to the current Score column.
- [x] Truncate to 5 submissions.

**Comment by nixpulvis** [comment]
@blerner Unless I'm mistaken the order is already most recent submission on the left. Is this what you wanted?

**Comment by blerner** [comment]
Overall, things look pretty good.  Some comments:

1. What's the URL to get to this dashboard, now?  There seem to be two, as a student: the homepage, http://107.170.114.15:3000/, and then the page available from Your Courses, http://107.170.114.15:3000/courses/1.  Those two pages look quite different at the moment, and neither looks quite like the screenshot above any more.  Could they look the same?  Or are they deliberately different?  The latter seems distinctly less helpful than the former.

2. On the former link, http://107.170.114.15:3000, when I mouseover the submissions from left-to-right, I get "Sub 0", "Sub 1", "Sub 2", etc -- this is the reversed order from what I mean.

3. If I go to a particular assignment, say http://107.170.114.15:3000/courses/1/assignments/2, I can see all my submissions, but they're timestamped rather than named, and there's no differentiation between the most recent one that was graded, and any of the others.  Can they be separated (e.g. two sections, "Graded submission" and "Older submissions")?

4. There's some error handling that needs to happen -- if I give a bogus url, say http://107.170.114.15:3000/courses/1/assignments/7/, or http://107.170.114.15:3000/courses/50, I shouldn't get an ActiveRecord error...  (You can bet that students will try to type in weird things, to see if they can't access data that isn't theirs.)

5.Could there be a Little Bobby Tables error here, if I try to go to `http://107.170.114.15:3000/courses/'' OR TRUE` or something?  (Dunno the exact syntax offhand right now)

6. Do you still have two courses' worth of dummy data to play with?  So far every student seems to have only one course, so I can't tell what changes you've made to the display when there are actually multiple courses.

**Comment by nixpulvis** [comment]
1. The original course page was a quick revision of what was there before. I agree that the dashboard and the course pages are now overlapping in functionality. I'm not sure what's the best course of action for this. Part of me feels like there should be a course page, but part of me wishes to remove the duplication.
2. Understood about the order.
3. "Older submissions" might not make sense if the graded assignment was submitted before another submission. Also there is nothing keeping multiple submissions from being graded, there is however a notion of a `BestSub` which is the highest graded submission. We could show the "Best Submission" and then "All Submissions", I think that follows from the data model a bit better.
4. Error handling in production mode is different than in development mode. I currently have the server in dev mode. When an error happens in production mode you get a mode standardized 404 or 500 page.
5. Rails does a pretty good job of making SQL injection attacks hard to have. In this case the Rails router would escape the string correctly.

The spam_db script I ran only creates one course. I'd be happy to add another course for you, or you can set one up.

**Comment by blerner** [comment]
To my mind, a "dashboard" might have things like "Current courses" and "Older courses" sections, and in the current section, have alerts for upcoming homeworks and let you submit assignments, or show the most recently graded assignment; whereas the course page itself would show all assignment details, allow you to drop the course, submit homeworks, or whatever.  But for now, since they're so overlapping, let's eliminate the course page, and focus on making the dashboard be particularly useful.  

I don't think I want a notion of "BestSub", per se.  WebCAT has a notion of "Show grade to student", and only one submission can have that flag set (in theory, modulo WebCAT foibles).  Could there be a notion of "Graded submission" and "Other submissions"?

Please create two more courses, with students and assignments and submissions and notes and grades and whatnot, so we can see what the UI generally looks like with more data.

**Comment by nixpulvis** [comment]
I'll leave the code for the course pages as is for now, but just make them not possible to get to from navigation.

If we're going to change the way submissions grades are represented in the database we should talk a bit more about it. Currently there is a whole database object called `BestSub` for performance reasons. I'm ok with changing things, but I want to make sure we're on the same page first. My current understanding is that you want all submissions to have grades (which could be null), then on a non-null submission grade, we can tell the system to "use" that grade. Now that submission shows up to the student as the submission that was graded and will be used for final grades. This is actually pretty close to the way things work with BestSub, only that best submissions are determined automatically.

I'll create some more data right now.

**Comment by blerner** [comment]
Ok, let's talk grading, and autograding, and choosing submissions.  I'll call each thing-that-provides-part-of-a-grade to be a "grader"; dunno what the internal term for it is.  Some graders should run on every single submission: style checking, unit tests, etc.  Some graders should run only when manually triggered: TA/tutor grading, or hypothetically we could have white-box and black-box tests instead of just a single tests file and run the white-box tests always and the black-box tests manually.  (That doesn't exist now, I know; I'm making sure the system we're building is future-proof enough to support it.)  So when students submit a homework, they need to be able to see the automatically-run grades ASAP; that's how they get feedback about style or compilation errors.  But the TA comments need metagrading, though.  So this implies that different graders need independent "show-to-students?" flags, and every submission can have some graders complete and some graders incomplete.

Once we have the TA/tutors grade the code (with comments, point deductions, etc), and once we run any remaining manually-triggered graders, in theory there should be at least one submission for every student that has every grader completed...but there might be more than one, because of unforeseen quirks that week (e.g. a student submits with a partner, a tutor grades it proactively, then a prof resubmits for the student for whatever reason, and now the new submission needs grades too).  So we need to mark a particular submission as "released to student", which marks that submission as being the one whose total grade gets reported in the student's grades.  This sounds fairly close to "BestSub", except yes, it's being determined manually instead of automatically.

We also need a way to handle grade complaints and regrades, which means that manually entered grades must be updatable, even after grades are released to student.  I don't recall whether you'd told me if this part of the system obeys the general immutability guide or not.

**Comment by nixpulvis** [comment]
Ok this is going to involve pretty much redoing the way grading works (not a bad thing). The way I see it we've got a grade matrix.

| | Staff Grader | Meta Grader | Style | Unit Test | 
| === | === | === | === | === |
| Submission 2| no | no | no | no |
| Submission 2| no | no | yes | yes |
| Submission 1| yes | no | yes | yes |

Then like you mentioned we should be able to flag a submission as the released submission. This process will be really tedious is done manually though, how are you imaging it working when time comes to release the grades?

In terms of regrades, I'd be ok with either of two options I see.

1. Allow grades to be updated. This adds mutation to the system, but it should be fine.
2. Make regrades be a new submission, this is less good in the sense that the contents of the submission should really always be duplicates.

**Comment by blerner** [comment]
Metagrading won't be its own grader, in that it doesn't contribute points to the final assignment grade.  Metagrading is just the TAs spot-checking the tutor grades, and sending emails to the profs or the tutors directly.  I'd update your matrix to include a boolean column "Released", with the invariant that there is at most one "Yes" in that column per student.  (Saying "per student" pointed out a subtlety to me: the table above is per student also, correct?  Otherwise having a notion of what the relevant "submissions 1, 2, 3" even are is tricky -- because of partner breakups and new partnerships, etc.)  I say "at most one" because there are initially none, until we metagrade and say "yup, looks good", and then selecting one to be released should mark all the other submissions as un-released.  (It's occasionally possible that students beg to "please grade the submission just before the deadline that doesn't quite work, instead of the late one after the deadline that works slightly better", so we may occasionally have to change which submission is marked as Released.)

In terms of releasing grades, I'd like a magic button on the staff assignment page that says "Release all completely-graded assignments", and then: for each student for this assignment, finds the unique submission that has all graders complete and marks it Released.  It should report all students for whom there are zero such completely-graded submissions ("WARNING: These students have not been graded yet!"), and it should separately report all students for whom there are two or more ("WARNING: These students have multiple grades -- pick one manually!").  This is about three steps better than WebCAT's solution, which does...something...and reports no errors ever.

In terms of regrades: I'd like to see 1a, grades can be updated, but there should be an audit log that records a tuple (studentID, assignmentID, submissionID, graderID, <who changed>, timestamp, oldGrade, newGrade) for every grader that runs.  (I don't have a good name to distinguish "graders"-meaning-style-or-tests from "graders"-meaning-tutors.  Names are hard.)  That log doesn't have to be directly viewable right now; I'll write a report generator later if I need it.  I don't want to create cloned submissions; that seems disingenuous and confusing to students.

**Comment by nixpulvis** [comment]
Ok, here's the matrix without meta-grading. But I'm not sure I'm going to make released a column, it might just be a color, or another section somewhere. With meta-grading out, how do we tell when it has been done?

|  | Staff Grader | Style | Unit Test | 
| --- | --- | --- | --- | --- |
| Submission 3 | no | no | no |
| Submission 2 | no | yes | yes |
| Submission 1| yes | yes | yes |

In terms of the "per student" issue, I was imaging that as a per student table yes, but now I'm concerned about teams. Submissions for a team that is not active (possibly because it was dissolved) should not show up even if they exist? For example maybe me and my partner submit for HW1, then we get into a huge fight before the deadline, and we request to be broken up, does our team submission still count?

For grade releasing I can see a button for "Release All" that then marks via colors or check boxes or something students/teams that need manual work, and those without grades. For the UI we could have all submissions grouped by either team or student for each assignment.

Ok, so just to be clear on the regrading, you're happy as long as the update is logged, with some sane naming?

**Comment by blerner** [comment]
In terms of *UI*, I don't care if it's a color or a column or whatever.  I was talking about it in terms of the data model -- logically speaking, there exists a table like the above (that can be stored directly, or computed), and that logical table needs a boolean column describing which row is released.

Submissions for a team that's been dissolved definitely *should* show up for the students involved.  Take our classic example, of A & B in a team, and submit subAB1 and subAB2.  Then the team is dissolved, and A teams up with C and submits subAC1 and subAC2.  So student A should see *four* submissions, namely subAB1, subAB2, subAC1 and subAC2, with the latter being the newest one.

It's an interesting question whether subAB1 and subAB2 should be allowed to be Released for either A or B.  I think not; that was the point of divorces.  Do you have enough information in the database to be able to "disable" submissions from divorced teams?

I'm ok with the regrading as long as there's understandable logging.

I don't follow your grade-releasing UI suggestion.  If I go to http://107.170.114.15:3000/staff/courses/1/assignments/3, say, there should be big "Release All" button at the top that does what I outlined above. It may need to take me to a new page, ...courses/1/assignments/3/release, say, that shows me the two groupings of Not-yet-graded students and Multiply-graded students.

Once I go back to courses/1/assignments/3, then yes, the color-coding of students by release status makes sense.  Was that what you meant?

**Comment by nixpulvis** [comment]
Ok discussion on this issue has kinda gotten off track. But yes that's what I meant.

Back to the issue of the student portal, I'm still confused with what you want with the order of the labels. Right now the most recent submission is on the left, since it always has a higher id.

**Comment by nixpulvis** [comment]
I've also updated the screenshot to reflect changes.

**Comment by blerner** [comment]
![wrong-order](https://cloud.githubusercontent.com/assets/918464/15977684/2d8d3562-2f28-11e6-845f-9c36af9c1de9.png)
If I mouse over the left item, I get "sub 0". If I mouse over the next item, I get "sub 1".  This is backwards, unless your generated data has wacky-backwards names.

**Comment by blerner** [comment]
Other problems: 

- [ ] if I go to http://107.170.114.15:3000/staff/courses/1/assignments/3 as staff, the "Attempts" column still just says "5 ( )" with no useful information.  
- [ ] If I click on the View link for any student on that page, I'll get taken to...one of their submissions, but I have no way of knowing which one, nor can I see the others.
- [ ] http://107.170.114.15:3000/staff/courses/1/assignments/3/submissions/2019 triggers a weird error for me.
- [ ] if I go to http://107.170.114.15:3000/courses/1/assignments/3 as a student (or impersonating one, anyway), I still don't see submission names, corresponding to whatever I saw on the previous screen.
- [ ] if I go to http://107.170.114.15:3000/ as a student (or impersonating one), the assignments are in the wrong order

I'm sure there are other problems; these are the ones I'm seeing on first notice.  (No student has a homework that contains a file, so I can't see what those look like yet, for instance.)

**Comment by blerner** [comment]
If you think this discussion has gotten off track, figure out how to merge issues #6 and #7 into a discussion about graders and grading and what the data model for them should be, and copy the notes from here into that.  I don't want to chase conversations through several issues.

**Comment by nixpulvis** [comment]
I agree, I'm having a lot of trouble finding the information I need as is. For example most of the checkboxes you just added are not related to this issue.

**Comment by blerner** [comment]
Every single checkbox I added was a problem I faced trying to use the student portal and figure out grades and submissions from students.  IF you want to file them all as separate bugs, be my guest -- I don't care, so long as they get fixed.

**Comment by nixpulvis** [comment]
> if I go to http://107.170.114.15:3000/staff/courses/1/assignments/3 as staff, the "Attempts" column still just says "5 ( )" with no useful information.

How is this related to the student potral?

**Comment by blerner** [comment]
Well, I got to that URL as a student, and saw nothing useful for me (as a prof).  So I stopped impersonating, and went back to see if there was anything useful.  There was even less.  Nathan, I don't care if you don't think this is is related to the student portal.  Move it to another issue.  Your job is to implement these features; my job is to find the problems and make sure the end product is what we need it to be, not wrangle Github issues.  I'm telling you these are the things I tried after the student portal was uninformatively useless to me; that's how they're related.

**Comment by nixpulvis** [comment]
Ben, I'm really trying to keep sense of the feedback on what does and doesn't work. There are a million problems though, and if I can't focus on one thing at a time it's frankly to overwhelming. I get nothing done when I try to fix everything at once. I was hoping to leave the GitHub issues as a papertrail for what is left to do at the end of the month.

Overall we just simply do not work well together, I'm not sure what other strategies I can try to make this work better between us.

**Comment by nixpulvis** [comment]
Ok, back to the student portal...

Do you have thoughts about the colors of things. Bootstrap for example has defined the notion of success, warning, and danger colors. We could use them for the grades pretty logically. I worry about also using them for due dates on the same page however.

**Comment by blerner** [comment]
I don't much care about CSS right now; presumably that's easy for me to fix in a CSS file later, if needed?

**Comment by nixpulvis** [comment]
Ok then I'll remove that from the list, and close this issue.
